# Generated by Django 2.1 on 2018-08-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000000)),
                ('tags', models.CharField(max_length=1000000)),
                ('url', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
